In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
vocab_size=10000

In [6]:
one_hot_repr=[one_hot(words,vocab_size)for words in sent]
one_hot_repr

[[6174, 3814, 42, 4403],
 [6174, 3814, 42, 243],
 [6174, 1161, 42, 1588],
 [5839, 2948, 1901, 7813, 615],
 [5839, 2948, 1901, 7813, 3002],
 [1194, 6174, 5785, 42, 5422],
 [2806, 8917, 6197, 7813]]

In [7]:

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6174 3814   42 4403]
 [   0    0    0    0 6174 3814   42  243]
 [   0    0    0    0 6174 1161   42 1588]
 [   0    0    0 5839 2948 1901 7813  615]
 [   0    0    0 5839 2948 1901 7813 3002]
 [   0    0    0 1194 6174 5785   42 5422]
 [   0    0    0    0 2806 8917 6197 7813]]


In [9]:
dim =10

In [15]:
model=Sequential()
model.add(Embedding(vocab_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [16]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [17]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step


array([[[-0.00013191,  0.00812083,  0.01444867, -0.04740552,
          0.01468809,  0.04940096,  0.03184373, -0.04607924,
         -0.00151389,  0.00048765],
        [-0.00013191,  0.00812083,  0.01444867, -0.04740552,
          0.01468809,  0.04940096,  0.03184373, -0.04607924,
         -0.00151389,  0.00048765],
        [-0.00013191,  0.00812083,  0.01444867, -0.04740552,
          0.01468809,  0.04940096,  0.03184373, -0.04607924,
         -0.00151389,  0.00048765],
        [-0.00013191,  0.00812083,  0.01444867, -0.04740552,
          0.01468809,  0.04940096,  0.03184373, -0.04607924,
         -0.00151389,  0.00048765],
        [-0.02347589,  0.03438203,  0.01867126,  0.00752638,
          0.02333803,  0.0257211 , -0.00685636,  0.02774412,
         -0.00331857,  0.01390027],
        [-0.00061114,  0.02766813, -0.03626733, -0.04216386,
          0.02937872,  0.04096569,  0.010541  , -0.00907781,
         -0.04619181, -0.01595358],
        [ 0.02693031,  0.04421074,  0.02741479, -0.0

In [19]:
embedded_docs[0]

array([   0,    0,    0,    0, 6174, 3814,   42, 4403], dtype=int32)

In [21]:
model.predict([embedded_docs[0]])

/home/riddhesh/genrative_ai_course/Generative-AI-Course/rnn_project/myenv/lib/python3.10/site-packages/keras/src/models/functional.py:241: UserWarning: The structure of `inputs` doesn't match the expected structure.
Expected: keras_tensor
Received: inputs=('Tensor(shape=(8,))',)
  warnings.warn(msg)


ValueError: Exception encountered when calling Sequential.call().

Invalid input shape for input Tensor("sequential_3_1/Cast:0", shape=(8,), dtype=float32). Expected shape (7, 8), but input has incompatible shape (8,)

Arguments received by Sequential.call():
  • inputs=('tf.Tensor(shape=(8,), dtype=int32)',)
  • training=False
  • mask=('None',)
  • kwargs=<class 'inspect._empty'>